### PR TITLE
Add wirepicksmsprovider

### PR DESCRIPTION
**Pull request by francisguchie**
This implementation is for https://www.wirepick.com/

### CODE REVIEW

**Comment by awasum** [comment]
You tested this with Fineract 1.x? @francisguchie 
Does it send messages?

**Comment by francisguchie** [comment]
@awasum 
Yes i am using it already using the SMS Campaign Module only 
But you should know that fineract 1.x has a code issue with the Webhooks. The webhooks modules has a code problem and needs to be address

I used MifosX realeases  18.03.01 and 17.07.01 -- these builds both have a problem in the code of webhooks but the SMS Campaign module is ok

**Comment by awasum** [comment]
Ok..Join the mailing list for Mifos and Fineract and start a discussion around these problems with use cases, examples.
Also create issues for them here: https://issues.apache.org/jira/projects/FINERACT

Also does it mean, you cans end SMS messages automatically from Mifos X App via this message gateway?

**Comment by francisguchie** [comment]
Also does it mean, you cans end SMS messages automatically from Mifos X App via this message gateway?
Yes i am using it already 

i am using the sms campaigns  messages are being sent 
there is not call back for the moment once am done it will be ready too

**Pull request closed without merging**
