### PR TITLE
Wirepick

### PR DESCRIPTION
**Pull request by francisguchie**
This implementation is for https://www.wirepick.com/

### CODE REVIEW

**Comment by luckyman20** [comment]
@francisguchie Can you please squash all the commits?

**Comment by francisguchie** [comment]
@luckyman20 

i need to know the best command to squash as i have never done it - checked on google but many options i dont know which one is more accurate

**Comment by luckyman20** [comment]
@francisguchie I myself haven't tried squash on git CLI.

There is a very easy way to do on `GitKraken`. (I am not endorsing the product in any way)

**Comment by francisguchie** [comment]
Let me use the CLI 
i think i will manage to solve it

**Comment by awasum** [comment]
@francisguchie Here is a link on how to squash commits: https://github.com/wprig/wprig/wiki/How-to-squash-commits

**Pull request closed without merging**
